_merge: deep

# Image
image:
  retina:
    desktop: true

# Javascript
carousel: false
bootstrap:
  modal: false
map: false

# Brand
brand:
  name: Handify
  # email: handify@uncinq.dev
  url: handify.io
  your:
    of: de votre entreprise du bâtiment
    to: à votre entreprise du bâtiment